# Generated by Django 5.2.5 on 2026-01-26 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingresos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresosextra',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_extra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingresosfijos',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_fijos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingresopago',
            name='ingreso_fijo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ingresos.ingresosfijos'),
        ),
    ]
