# Generated by Django 5.2.5 on 2026-02-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresopago',
            name='novelty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingresopago',
            name='novelty_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ingresopago',
            name='novelty_reason',
            field=models.TextField(default=''),
        ),
    ]
