# Generated by Django 5.2.5 on 2025-09-29 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0004_alter_ingresosfijos_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingreso_fijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ingresos.ingresosfijos')),
            ],
            options={
                'verbose_name_plural': 'Pagos de Ingresos',
            },
        ),
    ]
