# Generated by Django 5.2.5 on 2025-09-29 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EgresosExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresos_extra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Egresos Extra',
            },
        ),
        migrations.CreateModel(
            name='EgresosFijos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresos_fijos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Egresos Fijos',
            },
        ),
    ]
