# Generated by Django 5.2.5 on 2026-02-03 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('novelty', models.IntegerField(default=0)),
                ('novelty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('novelty_reason', models.TextField(default='')),
                ('egreso_fijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='egresos.egresosfijos')),
            ],
            options={
                'verbose_name_plural': 'Pagos de Egresos',
            },
        ),
    ]
