# Generated by Django 5.2.5 on 2025-09-29 15:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ahorros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_final', models.DateField(blank=True, null=True)),
                ('period', models.CharField(default='Mensual', max_length=100)),
                ('accrued', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('missing', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ahorros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ahorros',
            },
        ),
        migrations.CreateModel(
            name='AhorroMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ahorro_movimientos', to=settings.AUTH_USER_MODEL)),
                ('ahorro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='ahorros.ahorros')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
