# Generated by Django 5.2.5 on 2026-01-26 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ahorros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ahorromovimiento',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ahorro_movimientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ahorros',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ahorros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ahorromovimiento',
            name='ahorro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='ahorros.ahorros'),
        ),
    ]
